language: cpp
sudo: required
compiler:
  - clang
  - gcc
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-4.9
	    - libbz2-dev
            - libgsasl7-dev
            - uuid-dev
            - libboost-all-dev
            - cmake
            - libgtest-dev
            - libevent-dev
            - libssl-dev
            - libprotobuf-dev
    	    - protobuf-compiler
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
script:
  - ./bootstrap-travis
