name: Ubuntu CICD Pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install g++ libbz2-dev libgsasl7-dev uuid-dev libboost-all-dev cmake libgtest-dev libevent-dev libssl-dev libprotobuf-dev protobuf-compiler
    - name: setup cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make
    - name: make test
      run: make test
