name: OSX CICD Pipeline

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: brew  install flex bison python3 boost autoconf automake libtool libevent unzip
    - name: setup environment
      run: brew link --force flex bison && python3 -m pip install --user --upgrade pip wheel
    - name: setup cmake
      run: mkdir build && cd build &&  cmake -DBUILD_PYTHON_TESTS=ON -DBUILD_JAR=ON -DPYTHON_ITERATOR_SUPPORT=ON .. 
    - name: make
      run: cd build && export HOMEBREW_NO_AUTO_UPDATE=1 && CMAKE_INCLUDE_PATH="/usr/local/opt/flex/include" && CMAKE_LIBRARY_PATH="/usr/local/opt/flex/lib;/usr/local/opt/bison/lib" && LDFLAGS="-L/usr/local/opt/bison/lib" && export PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH" && cmake --build .
    - name: make test
      run: cd build && ctest --debug
